"""
Streamlit UI for the Workout Plan Generator.

This module is intentionally kept free of prompt-building or API-calling
logic — that lives in prompts.py / workout_generator.py — so the UI layer
only deals with collecting input, validating it, and rendering output.
"""

from datetime import datetime

from dotenv import load_dotenv

# Must run before importing workout_generator: MODEL_NAME is read from the
# environment at that module's import time, so .env has to be loaded first.
load_dotenv()

import streamlit as st

from workout_generator import generate_workout_plan
from workout_models import WorkoutPlan, WorkoutRequest

GOAL_OPTIONS = ["Build muscle", "Lose fat", "General fitness", "Improve endurance"]
EXPERIENCE_OPTIONS = ["Beginner", "Intermediate", "Advanced"]
EQUIPMENT_OPTIONS = ["No equipment", "Home dumbbells", "Full gym"]

st.set_page_config(page_title="Workout Plan Generator", page_icon="🏋️", layout="centered")


def _init_session_state() -> None:
    st.session_state.setdefault("plan", None)
    st.session_state.setdefault("last_request", None)
    st.session_state.setdefault("error", None)


def _render_inputs() -> WorkoutRequest:
    st.subheader("Tell us about yourself")

    goal = st.selectbox("Fitness goal", GOAL_OPTIONS)
    experience = st.selectbox("Experience level", EXPERIENCE_OPTIONS)
    days_per_week = st.slider("Days available per week", min_value=1, max_value=7, value=3)
    equipment = st.selectbox("Equipment access", EQUIPMENT_OPTIONS)
    limitations = st.text_area(
        "Injuries or limitations (optional)",
        placeholder='e.g. "bad knees", "no overhead pressing", "lower back pain"',
    )

    return WorkoutRequest(
        goal=goal,
        experience=experience,
        days_per_week=days_per_week,
        equipment=[equipment],
        limitations=limitations.strip() if limitations else None,
    )


def _run_generation(request: WorkoutRequest, regenerate: bool = False) -> None:
    with st.spinner("Generating your plan..."):
        result = generate_workout_plan(request, regenerate=regenerate)

    if result.success:
        st.session_state["plan"] = result.plan
        st.session_state["last_request"] = request
        st.session_state["error"] = None
    else:
        st.session_state["error"] = result.error
        # Keep any previously successful plan visible rather than wiping it out.


def _render_summary_bar(request: WorkoutRequest) -> None:
    cols = st.columns(4)
    cols[0].metric("Goal", request.goal)
    cols[1].metric("Level", request.experience)
    cols[2].metric("Days/week", request.days_per_week)
    cols[3].metric("Equipment", ", ".join(request.equipment))


def _render_plan(plan: WorkoutPlan) -> None:
    st.subheader("Your Weekly Plan")

    if plan.disclaimer:
        st.warning(f"⚠️ {plan.disclaimer}")

    if plan.summary:
        st.caption(plan.summary)

    for i, day in enumerate(plan.days):
        with st.expander(f"📅 Day {day.day_number}: {day.focus}", expanded=(i == 0)):
            if day.warm_up:
                st.markdown(f"**🔥 Warm-up:** {day.warm_up}")

            table_rows = [
                {
                    "Exercise": ex.name,
                    "Sets": ex.sets,
                    "Reps": ex.reps,
                    "Notes": ex.notes or "",
                }
                for ex in day.exercises
            ]
            st.table(table_rows)

            if day.cool_down:
                st.markdown(f"**🧊 Cooldown:** {day.cool_down}")

    if plan.rest_recovery_note:
        st.info(f"💤 **Rest & Recovery:** {plan.rest_recovery_note}")


def _render_output() -> None:
    if st.session_state["error"]:
        st.error(st.session_state["error"])

    plan: WorkoutPlan = st.session_state["plan"]
    if plan:
        _render_plan(plan)

        col1, col2 = st.columns(2)
        with col1:
            if st.button("🔁 Regenerate (different variation)"):
                _run_generation(st.session_state["last_request"], regenerate=True)
                st.rerun()
        with col2:
            filename = f"workout_plan_{datetime.now().strftime('%Y%m%d_%H%M')}.md"
            st.download_button(
                "⬇️ Download plan (.md)",
                data=plan.to_markdown(),
                file_name=filename,
                mime="text/markdown",
            )


def main() -> None:
    _init_session_state()

    st.title("🏋️ Workout Plan Generator")
    st.caption(
        "Answer a few questions and get a personalized weekly workout plan, "
        "generated by an LLM via the Groq API."
    )

    request = _render_inputs()

    if st.button("Generate Plan", type="primary"):
        _run_generation(request, regenerate=False)

    if st.session_state["plan"]:
        st.divider()
        _render_summary_bar(st.session_state["last_request"])

    _render_output()


if __name__ == "__main__":
    main()
